# MPLAB IDE generated this makefile for use with GNU make.
# Project: test_1.mcp
# Date: Sat Jun 16 17:38:25 2018

AS = MPASMWIN.exe
CC = 
LD = mplink.exe
AR = mplib.exe
RM = rm

Exercise1_sol3.cof : Exercise1_sol3.o
	$(CC) /p16F84A "Exercise1_sol3.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"Exercise1_sol3.cof" /M"Exercise1_sol3.map" /W /x

Exercise1_sol3.o : Exercise1_sol3.asm ../../../../../Program\ Files\ (x86)/Microchip/MPASM\ Suite/p16F84A.inc
	$(AS) /q /p16F84A "Exercise1_sol3.asm" /l"Exercise1_sol3.lst" /e"Exercise1_sol3.err" /d__DEBUG=1

clean : 
	$(CC) "Exercise1_sol3.o" "Exercise1_sol3.hex" "Exercise1_sol3.err" "Exercise1_sol3.lst" "Exercise1_sol3.cof"

